# --- Created by Ebean DDL
# To stop Ebean DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table user (
  id                            bigint generated by default as identity not null,
  nick                          varchar(255),
  edad                          integer,
  bio_id                        bigint,
  version                       bigint not null,
  when_created                  timestamp not null,
  when_modified                 timestamp not null,
  constraint uq_user_bio_id unique (bio_id),
  constraint pk_user primary key (id)
);

create table user_address (
  id                            bigint generated by default as identity not null,
  parent_user_id                bigint,
  street                        varchar(255),
  version                       bigint not null,
  when_created                  timestamp not null,
  when_modified                 timestamp not null,
  constraint pk_user_address primary key (id)
);

create table user_bio (
  id                            bigint generated by default as identity not null,
  texto                         varchar(255),
  version                       bigint not null,
  when_created                  timestamp not null,
  when_modified                 timestamp not null,
  constraint pk_user_bio primary key (id)
);

alter table user add constraint fk_user_bio_id foreign key (bio_id) references user_bio (id) on delete restrict on update restrict;

create index ix_user_address_parent_user_id on user_address (parent_user_id);
alter table user_address add constraint fk_user_address_parent_user_id foreign key (parent_user_id) references user (id) on delete restrict on update restrict;


# --- !Downs

alter table user drop constraint if exists fk_user_bio_id;

alter table user_address drop constraint if exists fk_user_address_parent_user_id;
drop index if exists ix_user_address_parent_user_id;

drop table if exists user;

drop table if exists user_address;

drop table if exists user_bio;

