# --- Created by Ebean DDL
# To stop Ebean DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table user (
  id                            bigint generated by default as identity not null,
  nick                          varchar(255),
  pass                          varchar(255),
  version                       bigint not null,
  when_created                  timestamp not null,
  when_modified                 timestamp not null,
  constraint pk_user primary key (id)
);


# --- !Downs

drop table if exists user;

